Basecamp_2/config/routes.rb
Rails.application.routes.draw do
  resources :admin
  resources :sends
  resources :sders

  resources :works
  resources :volts
  resources :projects do
    resources :works
    resources :sders
  end
  root 'projects#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Basecamp_2/app/models/send.rb
class Send < ApplicationRecord
  belongs_to :sder
end

Basecamp_2/app/controllers/sends_controller.rb
class SendsController < ApplicationController
  before_action :set_send, only: %i[ show edit update destroy ]

  # GET /sends or /sends.json
  def index
    @sends = Send.all
  end

  # GET /sends/1 or /sends/1.json
  def show
  end

  # GET /sends/new
  def new
    @send = Send.new
  end

  # GET /sends/1/edit
  def edit
  end

  # POST /sends or /sends.json
  def create
    @send = Send.new(send_params)

    respond_to do |format|
      if @send.save
        format.html { redirect_to sder_url(@send.sder)}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sends/1 or /sends/1.json
  def update
    respond_to do |format|
      if @send.update(send_params)
        format.html { redirect_to send_url(@send) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @send.destroy

    respond_to do |format|
      format.html { redirect_to sder_path(@send.sder) }
    end
  end

  private
    def set_send
      @send = Send.find(params[:id])
    end

    def send_params
      params.require(:send).permit(:title, :sder_id)
    end
end

Basecamp_2/app/helpers/sends_helper.rb
module SendsHelper
end

Basecamp_2/app/views/sends/_form.html.erb
<br><br><br>
<div class="container">
	<div class="container__item">
  <%= form_with(model: send,class:"form") do |form| %>
      <%= form.text_field :title, class:"form__field", placeholder:"Your Message", required: true %>
      <%= form.text_field :sder_id, type: :hidden %>

      <%= form.submit class:"btn btn--primary btn--inside uppercase"%>
		<% end %>
	</div>


<style>
  :root {
  background: #f5f6fa;
  color: #9c9c9c;
  font: 1rem "PT Sans", sans-serif;
}

html,
body,
.container {
  height: 100%;
}

a {
  color: inherit;
}
a:hover {
  color: #7f8ff4;
}

.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.uppercase {
  text-transform: uppercase;
}

.btn {
  display: inline-block;
  background: transparent;
  color: inherit;
  font: inherit;
  border: 0;
  outline: 0;
  padding: 0;
  transition: all 200ms ease-in;
  cursor: pointer;
}
.btn--primary {
  background: #7f8ff4;
  color: #fff;
  box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1);
  border-radius: 2px;
  padding: 12px 36px;
}
.btn--primary:hover {
  background: #6c7ff2;
}
.btn--primary:active {
  background: #7f8ff4;
  box-shadow: inset 0 0 10px 2px rgba(0, 0, 0, 0.2);
}
.btn--inside {
  margin-left: -96px;
}

.form__field {
  width: 360px;
  background: #fff;
  color: #a3a3a3;
  font: inherit;
  box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1);
  border: 0;
  outline: 0;
  padding: 22px 18px;
}
</style>

Basecamp_2/app/views/sends/_send.html.erb
<div id="<%= dom_id send %>">
  <p>
    <strong>Title:</strong>
    <%= send.title %>
  </p>

  <p>
    <strong>Sder:</strong>
    <%= send.sder_id %>
  </p>

</div>

Basecamp_2/app/views/sends/edit.html.erb
<h1>Editing send</h1>

<%= render "form", send: @send %>

<br>

<div>
  <%= link_to "Show this send", @send %> |
  <%= link_to "Back to sends", sends_path %>
</div>

Basecamp_2/app/views/sends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sends</h1>

<div id="sends">
  <% @sends.each do |send| %>
    <%= render send %>
    <p>
      <%= link_to "Show this send", send %>
    </p>
  <% end %>
</div>

<%= link_to "New send", new_send_path %>

Basecamp_2/app/views/sends/new.html.erb
<h1>New send</h1>

<%= render "form", send: @send %>

<br>

<div>
  <%= link_to "Back to sends", sends_path %>
</div>

Basecamp_2/app/views/sends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @send %>

<div>
  <%= link_to "Edit this send", edit_send_path(@send) %> |
  <%= link_to "Back to sends", sends_path %>

  <%= button_to "Destroy this send", @send, method: :delete %>
</div>