Basecamp_2/config/routes.rb
Rails.application.routes.draw do
  resources :admin
  resources :sends
  resources :sders

  resources :works
  resources :volts
  resources :projects do
    resources :works
    resources :sders
  end
  root 'projects#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Basecamp_2/app/models/work.rb
class Work < ApplicationRecord
  belongs_to :project
end

Basecamp_2/app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: %i[ show edit update destroy ]

  # GET /works or /works.json
  def index
    @project = Project.find(params[:project_id])
    @work = @project.works.new
    @works = @project.works
  end

  # GET /works/1 or /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works or /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to project_works_url(@work.project)}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1 or /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to work_url(@work) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1 or /works/1.json
  def destroy
    @work.destroy

    respond_to do |format|
      format.html { redirect_to project_works_url(@work.project) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_params
      params.require(:work).permit(:title, :project_id)
    end
end

Basecamp_2/app/helpers/works_helper.rb
module WorksHelper
end

Basecamp_2/app/views/works/_form.html.erb
<div class="container">
	<div class="container__item">
    <%= form_with(model: work, class:"form") do |form| %>
       <%= form.text_field :title,class:"form__field", placeholder:"Your To-do", required: true %>
           <%= form.text_field :project_id, type: :hidden %>

       <%= form.submit class:"btn btn--primary btn--inside uppercase"%>
		<% end %>
	</div>


<style>

body{
    background: #f5f6fa;

}
a {
  color: inherit;
}
a:hover {
  color: #7f8ff4;
}

.container {
  height: 100%;

    background: #f5f6fa;
  color: #9c9c9c;
  font: 1rem "PT Sans", sans-serif;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.uppercase {
  text-transform: uppercase;
}

.btn {
  display: inline-block;
  background: transparent;
  color: inherit;
  font: inherit;
  border: 0;
  outline: 0;
  padding: 0;
  transition: all 200ms ease-in;
  cursor: pointer;
}
.btn--primary {
  background: #7f8ff4;
  color: #fff;
  box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1);
  border-radius: 2px;
  padding: 12px 36px;
}
.btn--primary:hover {
  background: #6c7ff2;
}
.btn--primary:active {
  background: #7f8ff4;
  box-shadow: inset 0 0 10px 2px rgba(0, 0, 0, 0.2);
}
.btn--inside {
  margin-left: -96px;
}

.form__field {
  width: 360px;
  background: #fff;
  color: #a3a3a3;
  font: inherit;
  box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1);
  border: 0;
  outline: 0;
  padding: 22px 18px;
}
</style>

Basecamp_2/app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render "form", work: @work %>

<br>

<div>
  <%= link_to "Show this work", @work %> |
  <%= link_to "Back to works", works_path %>
</div>

Basecamp_2/app/views/works/index.html.erb
<br><br><br>
<h1 align="center">To-Dos</h1>

<%= render "form", work: @work %>

<div id="works">
  <% @works.each do |work| %>
     <p align="center"><%= work.title %>
     <% if work.title %>
     <%= link_to work, "data-turbo-method": :delete do %>

    <i class="bi bi-trash3"></i>
     
     <% end %>
     <% end %>
     </p> 
  <% end %>
</div>
</div>


<%= link_to "Back", project_path(@project), class:"button-26"  %>

<style>
  .button-26 {
  margin-top: -518px;
  text-decoration: none;
  background: #adadad;
  border: 1px solid #adadad;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-26:hover,
.button-26:active {
  background-color: initial;
  background-position: 0 0;
  color: #adadad;
}

.button-26:active {
  opacity: .5;
}

.button-25 {
  text-decoration: none;
  background: #ffa642;
  border: 1px solid #ffa642;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}
</style>

Basecamp_2/app/views/works/new.html.erb
<%= render "form", work: @work %>


  <%= link_to "Back to works", works_path %>

Basecamp_2/app/views/works/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @work %>

<div>
  <%= link_to "Edit this work", edit_work_path(@work) %> |
  <%= link_to "Back to works", works_path %>

  <%= button_to "Destroy this work", @work, method: :delete %>
</div>