Basecamp_2/config/routes.rb
Rails.application.routes.draw do
  resources :admin
  resources :sends
  resources :sders

  resources :works
  resources :volts
  resources :projects do
    resources :works
    resources :sders
  end
  root 'projects#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Basecamp_2/app/models/sder.rb
class Sder < ApplicationRecord
  belongs_to :project
  has_many :sends, dependent: :destroy
end

Basecamp_2/app/controllers/sders_controller.rb
class SdersController < ApplicationController
  before_action :set_sder, only: %i[ show edit update destroy ]

  # GET /sders or /sders.json
  def index
    @project = Project.find(params[:project_id])
    @sders = @project.sders
  end

  # GET /sders/1 or /sders/1.json
  def show
    @project = @sder.project_id
    @send = @sder.sends.new
    @sends = @sder.sends
  end

  # GET /sders/new
  def new
    @project = Project.find(params[:project_id])
    @sder = Sder.new
  end
  
  # GET /sders/1/edit
  def edit
    @project = @sder.project
  end

  # POST /sders or /sders.json
  def create
    @sder = Sder.new(sder_params)

    respond_to do |format|
      if @sder.save
        format.html { redirect_to sder_url(@sder) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sders/1 or /sders/1.json
  def update
    respond_to do |format|
      if @sder.update(sder_params)
        format.html { redirect_to sder_url(@sder) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sder.destroy

    respond_to do |format|
      format.html { redirect_to project_sders_url(@sder.project) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sder
      @sder = Sder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sder_params
      params.require(:sder).permit(:title, :description, :project_id)
    end
end

Basecamp_2/app/helpers/sders_helper.rb
module SdersHelper
end

Basecamp_2/app/views/sders/_sder.html.erb
<div id="<%= dom_id sder %>">
  <p>
    <h1 align="center"><%= sder.title %></h1>
  </p>
  <h3 align="center"><%= sder.description %></h3>
    
  </p>

</div>

Basecamp_2/app/views/sders/edit.html.erb
<%= render "form", sder: @sder %>

Basecamp_2/app/views/sders/index.html.erb
<%= link_to "New Message Board", new_project_sder_path(@project), class:"button-27" %> <br>
<%= link_to "Back", project_path(@project), class:"button-26"  %>

<div class="container">

  <% @sders.each do |sder| %>
  <a class="card1" href="<%= sder_path(sder.id) %>">
    <h3><%= sder.title %></h3>
    <p class="small"><%= sder.description %></p>
    <div class="go-corner" href="#">
      <div class="go-arrow">
        →
      </div>
    </div>
  </a>
  <% end %>


    </div>
  </a>
</div>


<style>
.button-27 {
  /* margin-left: 1000px; */
  float: right;
  text-decoration: none;
  background: #76a5af;
  border: 1px solid #76a5af;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-27:hover,
.button-27:active {
  background-color: initial;
  background-position: 0 0;
  color: #76a5af;
}

.button-27:active {
  opacity: .5;
}

.button-26 {
  margin-top: -18px;
  text-decoration: none;
  background: #adadad;
  border: 1px solid #adadad;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-26:hover,
.button-26:active {
  background-color: initial;
  background-position: 0 0;
  color: #adadad;
}

.button-26:active {
  opacity: .5;
}

@import url("https://fonts.googleapis.com/css?family=Nunito:400,700");
* {
  transition: all 0.3s ease-out;
}

html,
body {
  height: 100%;
  font-family: "Nunito", sans-serif;
  font-size: 16px;
}

.container {
  width: 100%;
  height: 100%;
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
}

h3 {
  color: #262626;
  font-size: 17px;
  line-height: 24px;
  font-weight: 700;
  margin-bottom: 4px;
}

p {
  font-size: 17px;
  font-weight: 400;
  line-height: 20px;
  color: #666666;
}
p.small {
  font-size: 14px;
}

.go-corner {
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  width: 32px;
  height: 32px;
  overflow: hidden;
  top: 0;
  right: 0;
  background-color: #00838d;
  border-radius: 0 4px 0 32px;
}

.go-arrow {
  margin-top: -4px;
  margin-right: -4px;
  color: white;
  font-family: courier, sans;
}

.card1 {
  display: block;
  position: relative;
  max-width: 262px;
  background-color: #f2f8f9;
  border-radius: 4px;
  padding: 32px 24px;
  margin: 12px;
  text-decoration: none;
  z-index: 0;
  overflow: hidden;
      width: 237px;
}
.card1:before {
  content: "";
  position: absolute;
  z-index: -1;
  top: -16px;
  right: -16px;
  background: #00838d;
  height: 32px;
  width: 32px;
  border-radius: 32px;
  transform: scale(1);
  transform-origin: 50% 50%;
  transition: transform 0.25s ease-out;
}
.card1:hover:before {
  transform: scale(21);
}

.card1:hover p {
  transition: all 0.3s ease-out;
  color: rgba(255, 255, 255, 0.8);
}
.card1:hover h3 {
  transition: all 0.3s ease-out;
  color: #ffffff;
}

.card2 {
  display: block;
  top: 0px;
  position: relative;
  max-width: 262px;
  background-color: #f2f8f9;
  border-radius: 4px;
  padding: 32px 24px;
  margin: 12px;
  text-decoration: none;
  z-index: 0;
  overflow: hidden;
  border: 1px solid #f2f8f9;
}
.card2:hover {
  transition: all 0.2s ease-out;
  box-shadow: 0px 4px 8px rgba(38, 38, 38, 0.2);
  top: -4px;
  border: 1px solid #cccccc;
  background-color: white;
}
.card2:before {
  content: "";
  position: absolute;
  z-index: -1;
  top: -16px;
  right: -16px;
  background: #00838d;
  height: 32px;
  width: 32px;
  border-radius: 32px;
  transform: scale(2);
  transform-origin: 50% 50%;
  transition: transform 0.15s ease-out;
}
.card2:hover:before {
  transform: scale(2.15);
}

.card3 {
  display: block;
  top: 0px;
  position: relative;
  max-width: 262px;
  background-color: #f2f8f9;
  border-radius: 4px;
  padding: 32px 24px;
  margin: 12px;
  text-decoration: none;
  overflow: hidden;
  border: 1px solid #f2f8f9;
}
.card3 .go-corner {
  opacity: 0.7;
}
.card3:hover {
  border: 1px solid #00838d;
  box-shadow: 0px 0px 999px 999px rgba(255, 255, 255, 0.5);
  z-index: 500;
}

.card3:hover p {
  color: #00838d;
}
.card3:hover .go-corner {
  transition: opactiy 0.3s linear;
  opacity: 1;
}

.card4 {
  display: block;
  top: 0px;
  position: relative;
  max-width: 262px;
  background-color: #ffffff;
  border-radius: 4px;
  padding: 32px 24px;
  margin: 12px;
  text-decoration: none;
  overflow: hidden;
  border: 1px solid #cccccc;
}
.card4 .go-corner {
  background-color: #00838d;
  height: 100%;
  width: 16px;
  padding-right: 9px;
  border-radius: 0;
  transform: skew(6deg);
  margin-right: -36px;
  align-items: start;
  background-image: linear-gradient(-45deg, #8F479A 1%, #DC2A74 100%);
}
.card4 .go-arrow {
  transform: skew(-6deg);
  margin-left: -2px;
  margin-top: 9px;
  opacity: 0;
}
.card4:hover {
  border: 1px solid #CD3D73;
}
.card4 h3 {
  margin-top: 8px;
}

.card4:hover .go-corner {
  margin-right: -12px;
}
.card4:hover .go-arrow {
  opacity: 1;
}
</style>

Basecamp_2/app/views/sders/new.html.erb
<%= render "form", sder: @sder %>

Basecamp_2/app/views/sders/show.html.erb
<%= render @sder %>

<div>
  <%= link_to "Edit", edit_sder_path(@sder), class:"button-25" %> 
  <%= link_to "Back", project_sders_path(@project), class:"button-26" %>
  <%= button_to "Destroy", @sder, method: :delete, class:"button-24"  %>

</div>




<div>
<%= render "sends/form", send: @send %>
</div>

<div>
<% @sends.each do |send| %>
  <p align="center"><%= send.title %>
  <% if send.id %>
    
  <%= link_to send, "data-turbo-method": :delete do %>
<i class="bi bi-trash3"></i>
  
  <% end %>

  <% end %>
  </p>
<% end %>

</div>
</div>

<style>
.button-26 {
  margin-left: -1470px;
  text-decoration: none;
  background: #adadad;
  border: 1px solid #adadad;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-26:hover,
.button-26:active {
  background-color: initial;
  background-position: 0 0;
  color: #adadad;
}

.button-26:active {
  opacity: .5;
}

.button-25 {
  text-decoration: none;
  background: #ffa642;
  border: 1px solid #ffa642;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-25 {
  margin-left: 1430px;
  text-decoration: none;
  background: #ffa642;
  border: 1px solid #ffa642;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-25:hover,
.button-25:active {
  background-color: initial;
  background-position: 0 0;
  color: #ffa642;
}

.button-25:active {
  opacity: .5;
}

.button-25 {
  text-decoration: none;
  background: #ffa642;
  border: 1px solid #ffa642;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-24:hover,
.button-24:active {
  background-color: initial;
  background-position: 0 0;
  color: #FF4742;
}

.button-24:active {
  opacity: .5;
}

.button-24 {
  margin-left: 690px;
  margin-top: -63px;
  text-decoration: none;
  background: #FF4742;
  border: 1px solid #FF4742;
  border-radius: 6px;
  box-shadow: rgba(0, 0, 0, 0.1) 1px 2px 4px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-family: nunito,roboto,proxima-nova,"proxima nova",sans-serif;
  font-size: 16px;
  font-weight: 800;
  line-height: 16px;
  min-height: 40px;
  outline: 0;
  padding: 12px 14px;
  text-align: center;
  text-rendering: geometricprecision;
  text-transform: none;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: middle;
}

.button-24:hover,
.button-24:active {
  background-color: initial;
  background-position: 0 0;
  color: #FF4742;
}

.button-24:active {
  opacity: .5;
}
</style>